import { Injectable } from '@angular/core';
//import { Http } from '@angular/http';
import 'rxjs/add/operator/map';
import { Constants } from './../shared/app.constant';
//import { DeviceModel } from '../Models/ExportModelClass';

/*
  Generated class for the PcmParameterDataSaveServiceProvider provider.

  See https://angular.io/docs/ts/latest/guide/dependency-injection.html
  for more info on providers and Angular DI.
*/
@Injectable()
export class PcmParameterDataSaveServiceProvider {

  constructor() {
    console.log('Hello PcmParameterDataSaveServiceProvider Provider');
  }

  /** 
  * This is used to get input values list
  * @returns {JSON} regulatorSetupInputList - The regularsetup data
  */
  static getAllParametersList() {
    // regulatorlist 
    // 
    let allParameterValueList = [
      { 'pid': 1, 'name': Constants.values.swashAngle, 'channel': Constants.channels.standaloneSettingsChannel, 'subchannel': Constants.channels.sswashAngleSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 2, 'name': Constants.values.pressureRegulator, 'channel': Constants.channels.pressurePIDRegChannel, 'subchannel': Constants.channels.pressureRegSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 3, 'name': Constants.values.pPart, 'channel': Constants.channels.pressurePIDRegChannel, 'subchannel': Constants.channels.pPartPressureRegSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 4, 'name': Constants.values.pPartGain, 'channel': Constants.channels.pressurePIDRegChannel, 'subchannel': Constants.channels.pPartGainPressureRegSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 5, 'name': Constants.values.iPart, 'channel': Constants.channels.pressurePIDRegChannel, 'subchannel': Constants.channels.iPartPressureRegSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 6, 'name': Constants.values.iPartTime, 'channel': Constants.channels.pressurePIDRegChannel, 'subchannel': Constants.channels.iPartTimePressureRegSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 7, 'name': Constants.values.dPart, 'channel': Constants.channels.pressurePIDRegChannel, 'subchannel': Constants.channels.dPartPressureRegSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 8, 'name': Constants.values.dPartGain, 'channel': Constants.channels.pressurePIDRegChannel, 'subchannel': Constants.channels.dPartGainPressureRegSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 9, 'name': Constants.values.feedforwardPercentage, 'channel': Constants.channels.pressurePIDRegChannel, 'subchannel': Constants.channels.feedForwardPressureRegSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 10, 'name': Constants.values.positiveOperationPercentage, 'channel': Constants.channels.pressurePIDRegChannel, 'subchannel': Constants.channels.positiveOperationPressureRegSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 11, 'name': Constants.values.negativeOperationPercentage, 'channel': Constants.channels.pressurePIDRegChannel, 'subchannel': Constants.channels.negativeOperationPressureRegSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 12, 'name': Constants.values.errorLimitPercentage, 'channel': Constants.channels.pressurePIDRegChannel, 'subchannel': Constants.channels.errorLimitPressureRegSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 13, 'name': Constants.values.invertFeedbackDirection, 'channel': Constants.channels.pressurePIDRegChannel, 'subchannel': Constants.channels.invertFeedbackDirectionPressureRegSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 14, 'name': 'Forward Min Current', 'channel': Constants.channels.PWMSettingsChannel, 'subchannel': 7, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 15, 'name': 'Forward Max Current', 'channel': Constants.channels.PWMSettingsChannel, 'subchannel': 8, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 16, 'name': 'Reverse Min Current', 'channel': Constants.channels.PWMSettingsChannel, 'subchannel': 9, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 17, 'name': 'Reverse Max Current', 'channel': Constants.channels.PWMSettingsChannel, 'subchannel': 10, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 18, 'name': 'Coil Resistance' , 'channel': Constants.channels.PWMSettingsChannel, 'subchannel': 4, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 19, 'name': 'Dither Amplitude', 'channel': Constants.channels.PWMSettingsChannel, 'subchannel': 3, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 20, 'name': 'Dither Frequency', 'channel': Constants.channels.PWMSettingsChannel, 'subchannel': 2, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 21, 'name': 'Max Current Error', 'channel': Constants.channels.PWMSettingsChannel, 'subchannel': 11, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 22, 'name': 'Limp Home Ramp Time', 'channel': Constants.channels.PWMSettingsChannel, 'subchannel': 12, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 23, 'name': Constants.values.pPart, 'channel': Constants.channels.PWMSettingsChannel, 'subchannel': Constants.channels.pPartSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 24, 'name': Constants.values.pPartGain, 'channel': Constants.channels.PWMSettingsChannel, 'subchannel': Constants.channels.pPartGainSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 25, 'name': Constants.values.iPart, 'channel': Constants.channels.PWMSettingsChannel, 'subchannel': Constants.channels.iPartSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 26, 'name': Constants.values.iPartTime, 'channel': Constants.channels.PWMSettingsChannel, 'subchannel': Constants.channels.iPartTimeSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 27, 'name': Constants.values.integrationOffOverThisError, 'channel': Constants.channels.PWMSettingsChannel, 'subchannel': Constants.channels.integrationOffOverThisErrorSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 28, 'name': Constants.values.feedforwardPercentage, 'channel': Constants.channels.PWMSettingsChannel, 'subchannel': Constants.channels.feedforwardPercentageSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 29, 'name': Constants.values.swashAngleErrorLimitPercentage, 'channel': Constants.channels.PWMSettingsChannel, 'subchannel': Constants.channels.swashAngleErrorLimitPercentageSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 30, 'name': Constants.values.iinvertSwashAngleDirection, 'channel': Constants.channels.PWMSettingsChannel, 'subchannel': Constants.channels.invertSwashAngleDirectionSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 31, 'name': Constants.values.shutdownRamp, 'channel': Constants.channels.pressurePIDRegChannel, 'subchannel': Constants.channels.pressureRegSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 32, 'name': Constants.values.positiveRampForwardDirection, 'channel': Constants.channels.standaloneSettingsChannel, 'subchannel': Constants.channels.positiveRampForwardDirectionSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 33, 'name': Constants.values.negativeRampForwardDirection, 'channel': Constants.channels.standaloneSettingsChannel, 'subchannel': Constants.channels.negativeRampForwardDirectionSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 34, 'name': Constants.values.positiveRampReverseDirection, 'channel': Constants.channels.standaloneSettingsChannel, 'subchannel': Constants.channels.positiveRampReverseDirectionSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 35, 'name': Constants.values.negativeRampReverseDirection, 'channel': Constants.channels.standaloneSettingsChannel, 'subchannel': Constants.channels.negativeRampReverseDirectionSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 36, 'name': Constants.values.functionInput, 'channel': Constants.channels.standaloneAnalog1FunctionChannel, 'subchannel': Constants.channels.functionInputSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 37, 'name': Constants.values.warnMin, 'channel': Constants.channels.standaloneAnalog1FunctionChannel, 'subchannel': Constants.channels.warnMinSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 38, 'name': Constants.values.warnMax, 'channel': Constants.channels.standaloneAnalog1FunctionChannel, 'subchannel': Constants.channels.warnMaxSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 39, 'name': Constants.values.alarmMin, 'channel': Constants.channels.standaloneAnalog1FunctionChannel, 'subchannel': Constants.channels.alarmMinSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 40, 'name': Constants.values.alarmMax, 'channel': Constants.channels.standaloneAnalog1FunctionChannel, 'subchannel': Constants.channels.alarmMaxSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 41, 'name': Constants.values.functionInput, 'channel': Constants.channels.standaloneAnalog2FunctionChannel, 'subchannel': Constants.channels.functionInputSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 42, 'name': Constants.values.warnMin, 'channel': Constants.channels.standaloneAnalog2FunctionChannel, 'subchannel': Constants.channels.warnMinSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 43, 'name': Constants.values.warnMax, 'channel': Constants.channels.standaloneAnalog2FunctionChannel, 'subchannel': Constants.channels.warnMaxSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 44, 'name': Constants.values.alarmMin, 'channel': Constants.channels.standaloneAnalog2FunctionChannel, 'subchannel': Constants.channels.alarmMinSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 45, 'name': Constants.values.alarmMax, 'channel': Constants.channels.standaloneAnalog2FunctionChannel, 'subchannel': Constants.channels.alarmMaxSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 46, 'name': Constants.values.functionInput, 'channel': Constants.channels.standaloneAnalog3FunctionChannel, 'subchannel': Constants.channels.functionInputSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 47, 'name': Constants.values.warnMin, 'channel': Constants.channels.standaloneAnalog3FunctionChannel, 'subchannel': Constants.channels.warnMinSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 48, 'name': Constants.values.warnMax, 'channel': Constants.channels.standaloneAnalog3FunctionChannel, 'subchannel': Constants.channels.warnMaxSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 49, 'name': Constants.values.alarmMin, 'channel': Constants.channels.standaloneAnalog3FunctionChannel, 'subchannel': Constants.channels.alarmMinSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 50, 'name': Constants.values.alarmMax, 'channel': Constants.channels.standaloneAnalog3FunctionChannel, 'subchannel': Constants.channels.alarmMaxSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 51, 'name': Constants.values.functionInput, 'channel': Constants.channels.standaloneAnalog4FunctionChannel, 'subchannel': Constants.channels.functionInputSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 52, 'name': Constants.values.warnMin, 'channel': Constants.channels.standaloneAnalog4FunctionChannel, 'subchannel': Constants.channels.warnMinSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 53, 'name': Constants.values.warnMax, 'channel': Constants.channels.standaloneAnalog4FunctionChannel, 'subchannel': Constants.channels.warnMaxSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 54, 'name': Constants.values.alarmMin, 'channel': Constants.channels.standaloneAnalog4FunctionChannel, 'subchannel': Constants.channels.alarmMinSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 55, 'name': Constants.values.alarmMax, 'channel': Constants.channels.standaloneAnalog4FunctionChannel, 'subchannel': Constants.channels.alarmMaxSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 56, 'name': Constants.values.functionInput, 'channel': Constants.channels.standaloneAnalog5FunctionChannel, 'subchannel': Constants.channels.functionInputSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 57, 'name': Constants.values.warnMin, 'channel': Constants.channels.standaloneAnalog5FunctionChannel, 'subchannel': Constants.channels.warnMinSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 58, 'name': Constants.values.warnMax, 'channel': Constants.channels.standaloneAnalog5FunctionChannel, 'subchannel': Constants.channels.warnMaxSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 59, 'name': Constants.values.alarmMin, 'channel': Constants.channels.standaloneAnalog5FunctionChannel, 'subchannel': Constants.channels.alarmMinSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 60, 'name': Constants.values.alarmMax, 'channel': Constants.channels.standaloneAnalog5FunctionChannel, 'subchannel': Constants.channels.alarmMaxSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 61, 'name': Constants.values.functionInput, 'channel': Constants.channels.standaloneAnalog6FunctionChannel, 'subchannel': Constants.channels.functionInputSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 62, 'name': Constants.values.warnMin, 'channel': Constants.channels.standaloneAnalog6FunctionChannel, 'subchannel': Constants.channels.warnMinSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 63, 'name': Constants.values.warnMax, 'channel': Constants.channels.standaloneAnalog6FunctionChannel, 'subchannel': Constants.channels.warnMaxSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 64, 'name': Constants.values.alarmMin, 'channel': Constants.channels.standaloneAnalog6FunctionChannel, 'subchannel': Constants.channels.alarmMinSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 65, 'name': Constants.values.alarmMax, 'channel': Constants.channels.standaloneAnalog6FunctionChannel, 'subchannel': Constants.channels.alarmMaxSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 66, 'name': Constants.values.functionInput, 'channel': Constants.channels.standaloneFunctionPT100Channel, 'subchannel': Constants.channels.functionInputSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 67, 'name': Constants.values.warnMin, 'channel': Constants.channels.standaloneFunctionPT100Channel, 'subchannel': Constants.channels.warnMinSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 68, 'name': Constants.values.warnMax, 'channel': Constants.channels.standaloneFunctionPT100Channel, 'subchannel': Constants.channels.warnMaxSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 69, 'name': Constants.values.alarmMin, 'channel': Constants.channels.standaloneFunctionPT100Channel, 'subchannel': Constants.channels.alarmMinSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 70, 'name': Constants.values.alarmMax, 'channel': Constants.channels.standaloneFunctionPT100Channel, 'subchannel': Constants.channels.alarmMaxSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 71, 'name': Constants.values.functionInput, 'channel': Constants.channels.standaloneDigitalInput1FunctionChannel, 'subchannel': Constants.channels.functionInputSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 72, 'name': Constants.values.inverted, 'channel': Constants.channels.standaloneDigitalInput1FunctionChannel, 'subchannel': Constants.channels.invertedSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 73, 'name': Constants.values.functionInput, 'channel': Constants.channels.standaloneDigitalInput2FunctionChannel, 'subchannel': Constants.channels.functionInputSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 74, 'name': Constants.values.inverted, 'channel': Constants.channels.standaloneDigitalInput2FunctionChannel, 'subchannel': Constants.channels.invertedSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 75, 'name': Constants.values.functionInput, 'channel': Constants.channels.standaloneDigitalInput3FunctionChannel, 'subchannel': Constants.channels.functionInputSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 76, 'name': Constants.values.inverted, 'channel': Constants.channels.standaloneDigitalInput3FunctionChannel, 'subchannel': Constants.channels.invertedSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 77, 'name': Constants.values.functionInput, 'channel': Constants.channels.standaloneDigitalInput4FunctionChannel, 'subchannel': Constants.channels.functionInputSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 78, 'name': Constants.values.inverted, 'channel': Constants.channels.standaloneDigitalInput4FunctionChannel, 'subchannel': Constants.channels.invertedSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 79, 'name': Constants.values.functionInput, 'channel': Constants.channels.standaloneDigitalIO1FunctionChannel, 'subchannel': Constants.channels.functionInputSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo1Value  },
      { 'pid': 80, 'name': Constants.values.inverted, 'channel': Constants.channels.standaloneDigitalIO1FunctionChannel, 'subchannel': Constants.channels.invertedSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo1Value  },
      { 'pid': 81, 'name': Constants.values.functionInput, 'channel': Constants.channels.standaloneDigitalIO2FunctionChannel, 'subchannel': Constants.channels.functionInputSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo2Value  },
      { 'pid': 82, 'name': Constants.values.inverted, 'channel': Constants.channels.standaloneDigitalIO2FunctionChannel, 'subchannel': Constants.channels.invertedSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo2Value  },
      { 'pid': 83, 'name': Constants.values.functionInput, 'channel': Constants.channels.standaloneDigitalIO3FunctionChannel, 'subchannel': Constants.channels.functionInputSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo3Value  },
      { 'pid': 84, 'name': Constants.values.inverted, 'channel': Constants.channels.standaloneDigitalIO3FunctionChannel, 'subchannel': Constants.channels.invertedSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo3Value  },
      { 'pid': 85, 'name': Constants.values.functionInput, 'channel': Constants.channels.standaloneDigitalIO4FunctionChannel, 'subchannel': Constants.channels.functionInputSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo4Value  },
      { 'pid': 86, 'name': Constants.values.inverted, 'channel': Constants.channels.standaloneDigitalIO4FunctionChannel, 'subchannel': Constants.channels.invertedSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo4Value  },
      { 'pid': 87, 'name': Constants.values.functionInput, 'channel': Constants.channels.standaloneDigitalIO5FunctionChannel, 'subchannel': Constants.channels.functionInputSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo5Value  },
      { 'pid': 88, 'name': Constants.values.inverted, 'channel': Constants.channels.standaloneDigitalIO5FunctionChannel, 'subchannel': Constants.channels.invertedSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo5Value  },
      { 'pid': 89, 'name': Constants.values.functionInput, 'channel': Constants.channels.standaloneDigitalIO6FunctionChannel, 'subchannel': Constants.channels.functionInputSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo6Value  },
      { 'pid': 90, 'name': Constants.values.inverted, 'channel': Constants.channels.standaloneDigitalIO6FunctionChannel, 'subchannel': Constants.channels.invertedSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo6Value  },
      { 'pid': 91, 'name': Constants.values.functionInput, 'channel': Constants.channels.standaloneDigitalIO7FunctionChannel, 'subchannel': Constants.channels.functionInputSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo7Value  },
      { 'pid': 92, 'name': Constants.values.inverted, 'channel': Constants.channels.standaloneDigitalIO7FunctionChannel, 'subchannel': Constants.channels.invertedSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo7Value  },
      { 'pid': 93, 'name': Constants.values.functionInput, 'channel': Constants.channels.standaloneDigitalIO8FunctionChannel, 'subchannel': Constants.channels.functionInputSubChannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value  },
      { 'pid': 94, 'name': Constants.values.inverted, 'channel': Constants.channels.standaloneDigitalIO8FunctionChannel, 'subchannel': Constants.channels.invertedSubchannel, 'value': "", 'connectorname': Constants.values.DigitalIo8Value },
    ];
    return allParameterValueList;
  }


  static getAllParametersListIdMap() {
    // regulatorlist 
    // 
    let allParameterValueListIdMap = [
      { 'pid': 0, 'value': "" },
      { 'pid': 1, 'value': "" },
      { 'pid': 2, 'value': "" },
      { 'pid': 3, 'value': "" },
      { 'pid': 4, 'value': "" },
      { 'pid': 5, 'value': "" },
      { 'pid': 6, 'value': "" },
      { 'pid': 7, 'value': "" },
      { 'pid': 8, 'value': "" },
      { 'pid': 9, 'value': "" },
      { 'pid': 10, 'value': "" },
      { 'pid': 11, 'value': "" },
      { 'pid': 12, 'value': "" },
      { 'pid': 13, 'value': "" },
      { 'pid': 14, 'value': "" },
      { 'pid': 15, 'value': "" },
      { 'pid': 16, 'value': "" },
      { 'pid': 17, 'value': "" },
      { 'pid': 18, 'value': "" },
      { 'pid': 19, 'value': "" },
      { 'pid': 20, 'value': "" },
      { 'pid': 21, 'value': "" },
      { 'pid': 22, 'value': "" },
      { 'pid': 23, 'value': "" },
      { 'pid': 24, 'value': "" },
      { 'pid': 25, 'value': "" },
      { 'pid': 26, 'value': "" },
      { 'pid': 27, 'value': "" },
      { 'pid': 28, 'value': "" },
      { 'pid': 29, 'value': "" },
      { 'pid': 30, 'value': "" },
      { 'pid': 31, 'value': "" },
      { 'pid': 32, 'value': "" },
      { 'pid': 33, 'value': "" },
      { 'pid': 34, 'value': "" },
      { 'pid': 35, 'value': "" },
      { 'pid': 36, 'value': "" },
      { 'pid': 37, 'value': "" },
      { 'pid': 38, 'value': "" },
      { 'pid': 39, 'value': "" },
      { 'pid': 40, 'value': "" },
      { 'pid': 41, 'value': "" },
      { 'pid': 42, 'value': "" },
      { 'pid': 43, 'value': "" },
      { 'pid': 44, 'value': "" },
      { 'pid': 45, 'value': "" },
      { 'pid': 46, 'value': "" },
      { 'pid': 47, 'value': "" },
      { 'pid': 48, 'value': "" },
      { 'pid': 49, 'value': "" },
      { 'pid': 50, 'value': "" },
      { 'pid': 51, 'value': "" },
      { 'pid': 52, 'value': "" },
      { 'pid': 53, 'value': "" },
      { 'pid': 54, 'value': "" },
      { 'pid': 55, 'value': "" },
      { 'pid': 56, 'value': "" },
      { 'pid': 57, 'value': "" },
      { 'pid': 58, 'value': "" },
      { 'pid': 59, 'value': "" },
      { 'pid': 60, 'value': "" },
      { 'pid': 61, 'value': "" },
      { 'pid': 62, 'value': "" },
      { 'pid': 63, 'value': "" },
      { 'pid': 64, 'value': "" },
      { 'pid': 65, 'value': "" },
      { 'pid': 66, 'value': "" },
      { 'pid': 67, 'value': "" },
      { 'pid': 68, 'value': "" },
      { 'pid': 69, 'value': "" },
      { 'pid': 70, 'value': "" },
      { 'pid': 71, 'value': "" },
      { 'pid': 72, 'value': "" },
      { 'pid': 73, 'value': "" },
      { 'pid': 74, 'value': "" },
      { 'pid': 75, 'value': "" },
      { 'pid': 76, 'value': "" },
      { 'pid': 77, 'value': "" },
      { 'pid': 78, 'value': "" },
      { 'pid': 79, 'value': "" },
      { 'pid': 80, 'value': "" },
      { 'pid': 81, 'value': "" },
      { 'pid': 82, 'value': "" },
      { 'pid': 83, 'value': "" },
      { 'pid': 84, 'value': "" },
      { 'pid': 85, 'value': "" },
      { 'pid': 86, 'value': "" },
      { 'pid': 87, 'value': "" },
      { 'pid': 88, 'value': "" },
      { 'pid': 89, 'value': "" },
      { 'pid': 90, 'value': "" },
      { 'pid': 91, 'value': "" },
      { 'pid': 92, 'value': "" },
      { 'pid': 93, 'value': "" },
      { 'pid': 94, 'value': "" },
      { 'pid': 95, 'value': "" },

    ];
    return allParameterValueListIdMap;
  }



}
