/**
 * @name Constants
 * @description
 * Constants is a  file to store constant variables
 * validation messages, encryption key, global variables
 **/
export const Constants = {
    'messages': {
        'errorConnect': 'error connecting',
        'characteristicNotFound': 'characteristic not found',
        'connecting': 'Connecting',
        'scanningStopped': 'Scanning has stopped',
        'scaningStarted': 'Scanning Started',
        'ionViewDidLoadRegulatorSetupPage': 'ionViewDidLoad RegulatorSetupPage',
        'ionViewDidLoadSwashAngleSetupPage': 'ionViewDidLoad SwashAngleSetupPage',
        'ionViewDidLoadPressureRegulatorSetupPage': 'ionViewDidLoad PressureRegulatorSetupPage',
        'status': 'Status',
        'regulatorTypeStatus': 'RegulatorType: ',
        'feedForwardTypeStatus': 'Feed Forward Type: ',
        'propotionalRegStatus': 'Propotional Reg: ',
        'integrationRegStatus': 'IntegrationReg Type: ',
        'invertSwashAngleDirectionStatus': 'Invert SwashAngle Direction Type: ',
        'propotionalGainStatus': 'Propotional Gain Type: ',
        'integrationTimeStatus': 'Integration Time: ',
        'maxFeedbackDeviationStatus': 'Max Feedback Deviation: ',
        'forwardMinCurrentStatus': 'Forward Min Current Status:',
        'forwardMaxCurrentStatus': 'Forward Max Current Status:  ',
        'reverseMinCurrentStatus': 'Reverse Min Current Status:  ',
        'reverseMaxCurrentStatus': 'Reverse Max Current Status:  ',
        'coilResistanceStatus': 'Coil Resistance Status:  ',
        'ditherAmplitudeStatus': 'Dither Amplitude Status:  ',
        'ditherFrequencyStatus': 'Dither Frequency Status:  ',
        'maxCurrentErrorStatus': 'Max Current ErrorS tatus:  ',
        'limpHomeRampTimeStatus': 'Limp Home Ramp Time Status:  ',
        'saveParameters': 'Save parameters',
        'paramSavedSuccessfully': 'Parameters Saved Successfully',
        'maximumLimit': 'Maximum Limit',
        'maximumLimitReached': 'You have reached the maximum limit',
        'minimumLimit': 'Minimum Limit',
        'minimumLimitReached': 'You have reached the minimum limit',
        'increment': 'Increment ',
        'decrement': 'Decrement ',
        'dismiss': 'Dismiss',
        'feedForwardTitle': 'Feed forward',
        'proportionalGainTitle': 'Proportional gain',
        'integrationTimeTitle': 'Integration time',
        'maxFeedbackDeviationTitle': 'Max feedback deviation',
        'disconnected': 'disconnected',
        'Failed': "Failed",
        'ulOpen': '<ul>',
        'ulClose': '</ul>',
        'liOpen': '<li>',
        'liClose': '</li>',
        'alarmMinTitle': 'Alarm(min)',
        'alarmMaxTitle': 'Alarm(max)',
        'warningMinTitle': 'Warning(min)',
        'warningMaxTitle': 'Warning(max)',
        'enterValueMessage': 'Please enter the value to be set',
        'value': 'value',
        'enter': ' enter ',
        'and': ' and ',
        'cancel': 'cancel',
        'enterValueWithin': 'Please enter value within ',
        'functionInputStatus': 'Function Input ',
        'limitIssue': 'Limit Issue:',
        'enterValueToBeSet': 'Please enter the values to be set',
        'setpointVsSwashAngle': 'Setpoint vs swash angle',
        'setpointVsPressure': 'Setpoint vs pressure',
        'bluetoothConnection': 'Bluetooth Connection',
        'bluetoothConnectionMessage': 'Please check your bluetooth connection.',
        'connectorParamterSetupValuesListnull': 'connectorParamterSetupValuesList null',
        'analogInputParameterItemsnull': 'analogInputParameterItems null',
        'atmQuestionObjectListnull': 'atmQuestionObjectList null',
        'connectorSetupErrormessageListnull': 'connectorSetupErrormessageList null',
        'ok': 'Ok',
        'calibrationInputHeader': 'Calibration Input:',
        'pleaseApply': 'Please apply ',
        'calibrationInputSubheader': 'to input and then press OK.',
        'calibrationErrorStatus': 'Calibration Error Code',
        'apply': 'Apply',
        'proceed': 'Proceed',
        'alarmAndWarnInputListnull': 'alarmAndWarnInputList null',
        'valueListnull': 'valueList null',
        "alarmsListMapSelectedValuesListnull": "alarmsListMapSelectedValuesList null",
        'confirmHeader': 'Confirmation:',
        'confirmSubheader': 'Are you sure you want to ',
        'paramResetSuccessfully': 'Parameters reset Successfully',
        'paramLoadedSuccessfully': 'Parameters loaded Successfully',
        'logInputListnull': 'logInputList null',
        'PCMMockName': 'PCM Mock Data',
        'PCMMockID': 'PCM Mock Data',
        'PCMMockServiceID': 'PCM Mock Data',
        'PCMMockrssi': 'PCM Mock Data',
        'PCMMockCharacteristicId': 'PCM Mock Data',
        'shutdownRampStatus': 'Shutdown Ramp Status:',
        'positiveRampForwardDirectionStatus': 'Positive Ramp Forward Direction Status:',
        'negativeRampForwardDirectionStatus': 'negative Ramp Forward Direction Status:',
        'positiveRampReverseDirectionStatus': 'Positive Ramp Reverse Direction Status:',
        'negativeRampReverseDirectionStatus': 'Negative Ramp Reverse Direction Status:',
        'swashAngleTypeStatus': 'Swash Angle Type Status:',
        'pPartTypeStatus': 'P-Part Type Status:',
        'iPartTypeStatus': 'I-Part Type Status:',
        'invertSwashAngleDirectionTypeStatus': 'Invert SwashAngle Direction Type Status:',
        'pPartGainTypeStatus': 'P-part Gain Type Status:',
        'iPartTimeStatus': 'I-part Time Status:',
        'integrationOffOverThisErrorStatus': 'Integration Off Over This Error Status:',
        'feedforwardPercentageStatus': 'Feedforward Percentage Status:',
        'swashAngleErrorLimitPercentageStatus': 'Swash Angle Error Limit Percentage Status:',
        'pressureRegulatorTypeStatus': 'Pressure Regulator Type Status:',
        'dPartTypeStatus': 'D-Part Type Status:',
        'invertFeedbackDirectionPressureTypeStatus': 'Invert Feedback Direction Pressure Type Status:',
        'dPartGainTypeStatus': 'D-Part Gain Type Status:',
        'positiveOperationStatus': 'Positive Operation Status:',
        'negativeOperationStatus': 'Negative Operation Status:',
        'errorLimitPercentageStatus': 'Error Limit Percentage Status:',
        'alert': 'Alert',
        'pressureRegulatorOnAlert': 'The pressure regulator is also active, using two regulators might cause oscillation.',
        'swashAngleOnAlert': 'The swash angle regulator is also active, using two regulators might cause oscillation.',
        'undefined': 'Undefined',
        'saveToFileAlertHeader': 'Save',
        'saveToFileAlertMessageSuccess': 'Saved Successfully To File',
        'saveToFileAlertMessageFailed': 'Save To File Faled',
        'SavingFile': 'Saving File..',
        'LoadingFile': 'Loading File..',
        'FileLoadSuccess': 'File Loaded Successfully',
        'FileLoadSuccessHeader': 'File Load',
        'FileLoadFailed': 'Parameters Failed',
        'confirmLoadFileSubheader': 'Are you sure want to load data from file? Please choose an option',
        'FileCheckHeader': 'File Error',
        'FileCheckSubHeader': 'File does not exist',
        'emailSubheaderIOS1': 'Saved file ',
        'emailSubheaderIOS2': '.txt successfully To app memory.<br/>Click open file to view and add to Icloud',
        'pPartGainStatus': 'P-Part Gain Status:  ',
        'dPartGainStatus': 'D-Part Gain Status:  ',
        'minInputTitle': 'MinInput',
        'maxInputTitle': 'MaxInput',
        'sensorUnitTitle': 'Display Unit',
        'passwordTitle': 'Authentication:',
        'passwordSubTitle': 'Please enter the password for write access authentication',
        'removePasswordSubTitle': 'Are you sure to remove write access from the device?',
        'passwordPlaceholder': 'Enter password',
        'newPasswordPlaceholder': 'Enter new password',
        'newPasswordConfirmationPlaceholder': 'Re-enter new password',
        'authenticationFailureTitle': 'Authentication Failure:',
        'authenticationFailureSubtitle': 'Please check the password entered and try again.',
        'sensorUnitChangeHeader': 'Sensor Unit Change:',
        'sensorUnitChangeSubheader': 'Are you sure to change the sensor units?',
        'displayUnitTitle': 'Display Unit',
        'emailSubheaderAndroid': 'Saved the file Successfully to Downloads Folder.<br/>',
        'sendEmail': 'Send Email',
        'openFile': 'Open File',
        'enterFileNameToBeSet': 'Please enter the file name',
        'filepresentHeader': 'Override File:',
        'filepresentSubheader': 'Are you sure want to override previous file?',
        'newPasswordTitle': 'Password Setting:',
        'newPasswordSubTitle': 'Please set the new password',
        'passwordAuthHeader': 'Authentication:',
        'mockDataAuthHeader':'View mock Data',
        'mockDataSubheader':'This is to view Mock Data',
        'passwordAuthSubheaderSuccess': 'Password authentication successful.<br/>Write access to user granted.',
        'passwordAuthSubheaderFailure': 'Password authentication failed.<br/>Please try again.',
        'noPasswordSubheader': 'Please enter the password in <b>App settings</b> and try again.',
        'newPasswordNotMatching': 'New password entered does not match the re-enetered password.',
        'oldPasswordNotMatching': 'Old password entered,does not match.',
        'newPasswordSubheaderSuccess': 'Password change successful.',
        'newPasswordSubheaderFailure': 'Password change failure.<br/><br/>Please try again later.',
        'passworddeauthSubheaderSuccess': 'Password de-authentication successful.<br/>Write access to user removed.',
        'passworddeuthSubheaderFailure': 'Password de-authentication failed.<br/>Please try again.',
        'setParameters':'Set parameters',
        'calibrate':'Calibrate',
        'enableWrite':'Enable write',
        'clearLog':'Clear log',
        'switchToVal': 'Switch to value',
        'switchToCurrent': 'Switch to current',
        'newNumberPlaceholder': 'Enter new number',
        'numberChangeHeader':'PCM number change:',
        'numberChangeSubheaderSuccess':'PCM number changed. For this to take effect you need to save the configuration to EEPROM in device setup page and then restart PCM.',
        'numberChangeSubheaderFailure':'PCM number changed failed. Please try again.'


    },
    'values': {
        'characteristicIDToUse': 'f000c0e1-0451-4000-b000-000000000000',
        'deviceObject': 'deviceObject',
        'read': 'read',
        'write': 'write',
        'calibrate': 'calibrate',
        'regulatorType': 'regulatorType',
        'feedForward': 'feedForward',
        'propotionalReg': 'propotionalReg',
        'integrationReg': 'integrationReg',
        'invertSwashAngleDirection': 'invertSwashAngleDirection',
        'propotionalGain': 'propotionalGain',
        'integrationTime': 'integrationTime',
        'maxFeedbackDeviation': 'maxFeedbackDeviation',
        'one': 1,
        'green': 'green',
        'red': 'red',
        'stop': 'Stop',
        'run': 'Run',
        'LO': 'LO',
        'LI': 'LI',
        'O1': 'O1',
        'O2': 'O2',
        'AI': 'AI',
        'PT': 'PT',
        'X1': 'X1',
        'X2': 'X2',
        'X3': 'X3',
        'X4': 'X4',
        'DI': 'DI',
        'DO': 'DO',
        'PO': 'PO',
        'PI': 'PI',
        'USB': 'Mini USB',
        'connector': 'connector',
        'connectorValObj': 'connectorValObj',
        'AnalogIn1Value': 'Analog in 1',
        'AnalogIn2Value': 'Analog in 2',
        'AnalogIn1': 'AnalogIn1',
        'AnalogIn2': 'AnalogIn2',
        'workPressureInput': 3,
        'threshold': 4,
        'thresholdTemp': 5,
        'bar': 'bar',
        'celsius': 'Celsius',
        'revMin': 'Rev/min',
        'alarmMin': 'alarmMin',
        'alarmMax': 'alarmMax',
        'warnMin': 'warnMin',
        'warnMax': 'warnMax',
        'wType': 3,
        'rType': 2,
        'blink': 'blink',
        'alarm': 'Alarm',
        'quickstop': 'Quick stop',
        'runService': 'Run service',
        'Proportional': 'Proportional',
        'Integration': 'Integration',
        'liveTuneGraphType': 'liveTuneGraphType',
        'forwardMinCurrent': 'Forward min current',
        'forwardMaxCurrent': 'Forward max current',
        'reverseMinCurrent': 'Reverse min current',
        'reverseMaxCurrent': 'Reverse max current',
        'coilResistance': 'Coil resistance',
        'ditherAmplitude': 'Dither amplitude',
        'ditherFrequency': 'Dither frequency',
        'maxCurrentError': 'Max current error',
        'limpHomeRampTime': 'Limp home ramp time',
        'AnalogIn3Value': 'Analog in 3',
        'AnalogIn4Value': 'Analog in 4',
        'AnalogIn5Value': 'Analog in 5',
        'AnalogIn6Value': 'Analog in 6',
        'DigitalIn1Value': 'Digital in 1',
        'DigitalIn2Value': 'Digital in 2',
        'DigitalIn3Value': 'Digital in 3',
        'DigitalIn4Value': 'Digital in 4',
        'DIO': 'DIO',
        'AnalogIn': 'AnalogIn',
        'DigitalIn': 'DigitalIn',
        'PT100': 'PT100',
        'disabledFuncInput': 0,
        'DigitalIo1Value': 'Digital I/O 1',
        'DigitalIo2Value': 'Digital I/O 2',
        'DigitalIo3Value': 'Digital I/O 3',
        'DigitalIo4Value': 'Digital I/O 4',
        'DigitalIo5Value': 'Digital I/O 5',
        'DigitalIo6Value': 'Digital I/O 6',
        'DigitalIo7Value': 'Digital I/O 7',
        'DigitalIo8Value': 'Digital I/O 8',
        'inverted': 'inverted',
        'FactoryReset': 'do a factory reset',
        'SaveToEeprom': 'save to EEPROM',
        'LoadFromEeprom': 'load From EEPROM',
        'liveGraphSetpointValue': 'Setpoint',
        'liveGraphPressureValue': 'Pressure',
        'liveGraphSwashAngleValue': 'Swash angle',
        'liveGraphPumpCurrentValue': 'Pump current',
        'liveGraphAnalogInput1Value': 'Analog input 1',
        'liveGraphAnalogInput2Value': 'Analog input 2',
        'liveGraphAnalogInput3Value': 'Analog input 3',
        'liveGraphAnalogInput4Value': 'Analog input 4',
        'liveGraphAnalogInput5Value': 'Analog input 5',
        'liveGraphAnalogInput6Value': 'Analog input 6',
        'liveGraphPT100Value': 'PT100',
        'all': 'all',
        'Alarms': 'Alarms',
        'HardwareAlarms': 'HardwareAlarms',
        'Warnings': 'Warnings',
        'TempWarnings': 'TempWarnings',
        "E": "E",
        'AlarmsLog': 'AlarmsLog',
        'HardwareAlarmsLog': 'HardwareAlarmsLog',
        'WarningsLog': 'WarningsLog',
        'TempWarningsLog': 'TempWarningsLog',
        'shutdownRamp': 'Shutdown ramp',
        'positiveRampForwardDirection': 'Positive ramp forward direction',
        'negativeRampForwardDirection': 'Negative ramp forward direction',
        'positiveRampReverseDirection': 'Positive ramp reverse direction',
        'negativeRampReverseDirection': 'Negative ramp reverse direction',
        'swashAngle': 'Swash angle regulator on/off',
        'pPart': 'P-part on/off',
        'pPartGain': 'P-part gain',
        'iPart': 'I-part on/off',
        'iPartTime': 'I-part time',
        'integrationOffOverThisError': 'Integration off over this error',
        'feedforwardPercentage': 'Feedforward %',
        'swashAngleErrorLimitPercentage': 'Swash angle error limit %',
        'iinvertSwashAngleDirection': 'Invert swash angle direction',
        'dPartGain': 'D-part gain',
        'positiveOperationPercentage': 'Positive operation %',
        'negativeOperationPercentage': 'Negative operation %',
        'errorLimitPercentage': 'Error limit %',
        'pressureRegulator': 'Pressure regulator on/off',
        'dPart': 'D-part on/off',
        'invertFeedbackDirection': 'Invert feedback direction',
        "W": "W",
        'functionInput': "FunctionInput",
        'AnalogIn3': 'AnalogIn3',
        'AnalogIn4': 'AnalogIn4',
        'AnalogIn5': 'AnalogIn5',
        'AnalogIn6': 'AnalogIn6',
        "DigitalIn1": "DigitalIn1",
        "DigitalIn2": "DigitalIn2",
        "DigitalIn3": "DigitalIn3",
        "DigitalIn4": "DigitalIn4",
        "DigitalIO1": "DigitalIO1",
        "DigitalIO2": "DigitalIO2",
        "DigitalIO3": "DigitalIO3",
        "DigitalIO4": "DigitalIO4",
        "DigitalIO5": "DigitalIO5",
        "DigitalIO6": "DigitalIO6",
        "DigitalIO7": "DigitalIO7",
        "DigitalIO8": "DigitalIO8",
        "SaveToFile": "SaveToFile",
        "SaveFileName": "pcmparameterfile",
        "LoadToDevice": "LoadToDevice",
        'minInput': 'minInput',
        'maxInput': 'maxInput',
        'sensorUnit': 'sensorUnit',
        'graphUpdate': 'graphUpdate',
        'None': 0,
        'CelsiusUnitValue': 1,
        'FahrenheitUnitValue': 2,
        'BarUnitValue': 3,
        'PsiUnitValue': 4,
        'MpaUnitValue': 5,
        'RpmUnitValue': 6,
        'LUnitValue': 7,
        'LPerMinUnitValue': 8,
        'PercentageUnitValue': 9,
        'authenticate': 'authenticate',
        'displayUnit': 'displayUnit',
        'fileExtentionText': '.txt',
        'initializeStartNotify': 'initializeStartNotify',
        'newPassword': 'newPassword',
        'deAuthenticate': 'deAuthenticate',
        'ioSetupHeader':'ioSetupHeader',
        'ioSetup': 'I/O Setup',
        'ioOverview':'I/O Overview',
        'numberChangePCM':'numberChangePCM'
    },
    'channels': {
        'standaloneSettingsChannel': 40,
        'PWMSettingsChannel': 30,
        'calibrateAnalogInput': 41,
        'calibratePt100': 42,
        'calibrateAnalogOutput': 43,
        'pressurePIDRegChannel': 46,
        'analogIn1SubChannel': 0,
        'analogIn2SubChannel': 1,
        'analogIn3SubChannel': 2,
        'analogIn4SubChannel': 3,
        'analogIn5SubChannel': 4,
        'analogIn6SubChannel': 5,
        'pt100SubChannel': 0,
        'regTypeSubchannel': 13,
        'feedForwardSubchannel': 17,
        'propotionalRegSubchannel': 13,
        'integrationRegSubchannel': 14,
        'invertSwashAngleDirectionSubchannel': 22,
        'propotionalGainSubchannel': 15,
        'integrationTimeSubchannel': 16,
        'maxFeedbackDeviationSubchannel': 19,
        'alarmMinSubchannel': 4,
        'alarmMaxSubchannel': 5,
        'warnMinSubchannel': 6,
        'warnMaxSubchannel': 7,
        'standaloneAnalog1FunctionChannel': 50,
        'standaloneAnalog2FunctionChannel': 51,
        'functionInputSubChannel': 0,
        'runModeSubChannel': 4,
        'setPointSubChannel': 3,
        'swashAngleSubChannel': 14,
        'pressureSubChannel': 15,
        'forwardMinCurrentSubChannel': 7,
        'forwardMaxCurrentSubChannel': 8,
        'reverseMinCurrentSubChannel': 9,
        'reverseMaxCurrentSubChannel': 10,
        'coilResistanceSubChannel': 4,
        'ditherAmplitudeSubChannel': 3,
        'ditherFrequencySubChannel': 2,
        'maxCurrentErrorSubChannel': 11,
        'limpHomeRampTimeSubChannel': 12,
        'standaloneAnalog3FunctionChannel': 52,
        'standaloneAnalog4FunctionChannel': 53,
        'standaloneAnalog5FunctionChannel': 54,
        'standaloneAnalog6FunctionChannel': 55,
        'invertedSubchannel': 1,
        'standaloneFunctionPT100Channel': 56,
        'standaloneDigitalInput1FunctionChannel': 60,
        'standaloneDigitalInput2FunctionChannel': 61,
        'standaloneDigitalInput3FunctionChannel': 62,
        'standaloneDigitalInput4FunctionChannel': 63,
        'standaloneDigitalIO1FunctionChannel': 64,
        'standaloneDigitalIO2FunctionChannel': 65,
        'standaloneDigitalIO3FunctionChannel': 66,
        'standaloneDigitalIO4FunctionChannel': 67,
        'standaloneDigitalIO5FunctionChannel': 68,
        'standaloneDigitalIO6FunctionChannel': 69,
        'standaloneDigitalIO7FunctionChannel': 70,
        'standaloneDigitalIO8FunctionChannel': 71,
        'eepromFunctionChannel': 99,
        'saveToEepromSubChannel': 1,
        'loadFromEepromSubChannel': 2,
        'factoryResetSubChannel': 3,
        'liveGraphSetpointChannel': 40,
        'liveGraphPressureChannel': 40,
        'liveGraphSwashAngleChannel': 40,
        'liveGraphPumpCurrentChannel': 40,
        'liveGraphAnalogInput1Channel': 10,
        'liveGraphAnalogInput2Channel': 11,
        'liveGraphAnalogInput3Channel': 12,
        'liveGraphAnalogInput4Channel': 13,
        'liveGraphAnalogInput5Channel': 14,
        'liveGraphAnalogInput6Channel': 15,
        'liveGraphPT100Channel': 18,
        'liveGraphSetpointSubhannel': 3,
        'liveGraphPressureSubhannel': 15,
        'liveGraphSwashAngleSubhannel': 14,
        'liveGraphPumpCurrentSubhannel': 22,
        'liveGraphAnalogInput1Subhannel': 0,
        'liveGraphAnalogInput2Subhannel': 0,
        'liveGraphAnalogInput3Subhannel': 0,
        'liveGraphAnalogInput4Subhannel': 0,
        'liveGraphAnalogInput5Subhannel': 0,
        'liveGraphAnalogInput6Subhannel': 0,
        'liveGraphPT100Subhannel': 0,
        'alarmCommunucationChannel': 45,
        'warningsSubchannel': 4,
        'tempWarningsSubchannel': 5,
        'alarmsSubchannel': 7,
        'hardwareAlarmsSubchannel': 6,
        'warningsLogSubchannel': 8,
        'tempWarningsLogSubchannel': 9,
        'hardwareAlarmsLogSubchannel': 10,
        'alarmsLogSubchannel': 11,
        'firmwareVersion': 23,
        'sswashAngleSubChannel': 13,
        'pPartSubChannel': 13,
        'pPartGainSubChannel': 15,
        'iPartSubChannel': 14,
        'iPartTimeSubChannel': 16,
        'integrationOffOverThisErrorSubChannel': 18,
        'feedforwardPercentageSubChannel': 17,
        'swashAngleErrorLimitPercentageSubChannel': 19,
        'invertSwashAngleDirectionSubChannel': 22,
        'shutdownRampSubChannel': 12,
        'positiveRampForwardDirectionSubChannel': 16,
        'negativeRampForwardDirectionSubChannel': 17,
        'positiveRampReverseDirectionSubChannel': 18,
        'negativeRampReverseDirectionSubChannel': 19,
        'pressureRegSubChannel': 0,
        'pPartPressureRegSubChannel': 1,
        'pPartGainPressureRegSubChannel': 2,
        'iPartPressureRegSubChannel': 3,
        'iPartTimePressureRegSubChannel': 4,
        'dPartPressureRegSubChannel': 5,
        'dPartGainPressureRegSubChannel': 6,
        'feedForwardPressureRegSubChannel': 7,
        'positiveOperationPressureRegSubChannel': 8,
        'negativeOperationPressureRegSubChannel': 9,
        'errorLimitPressureRegSubChannel': 10,
        'invertFeedbackDirectionPressureRegSubChannel': 11,
        'minInputSubchannel': 1,
        'maxInputSubchannel': 2,
        'sensorUnitSubchannel': 3,
        'analogGraphSubChannel': 9,
        'authenticationChannel': 999,
        'authenticationsubchannel': 999,
        'liveGraphAnalogInputCurrentSubhannel': 0
    }

};